'use strict';
/*
 * template.js — the frozen per-quote page renderer for quotle.info.
 *
 * ONE canonical string drives every identity field (locked contract, CLAUDE.md 7 Jul 2026):
 *     https://quotle.info/who-said/{quoteSlug}
 * canonical, og:url, all Schema @ids, breadcrumb current node, cite permalink, and
 * prev/next/related all derive from it here — nothing is hand-written per page.
 *
 * Rendering renderPage(ulrichRecord) reproduces prototypes/quote-v3.html (regression anchor),
 * except the JSON-LD block, which is emitted programmatically (semantically identical).
 *
 * Sections gate on record fields:
 *   misattribution → only if record.misattribution
 *   context        → only if record.context
 *   related        → only if record.related?.length
 *   pager          → only if record.pager
 *   artifact       → per record.source.artifact (null → hidden)
 *   rights note    → per record.source.publicDomain (or explicit record.source.rightsNote)
 */

const { HEAD_SCRIPT, THEME_CSS, CONTROL, SCRIPT } = require('./a11y-widget');
const { ROOT_CSS } = require('./tokens');
const { esc } = require('./esc'); // one shared entity-aware escape (also used by build-index.js)
const { hasAuthorPage } = require('./authors'); // which authors have a /authors/{slug} profile
const { NAV: siteNav, CHROME_CSS, SEARCH_JS } = require('./chrome'); // shared nav + universal search

const ORIGIN = 'https://quotle.info';

// Author profiles at /authors/{slug} are generated by build-authors.js. Author names link there
// only for profile-able authors (real people, not the "anonymous"/"unknown" placeholder slugs) —
// hasAuthorPage() is the shared gate, so a name never links to a page that wasn't generated.
const AUTHORS_ENABLED = true;
const authorLinked = (slug) => AUTHORS_ENABLED && hasAuthorPage(slug);

// ---- small helpers -------------------------------------------------------
// escape only for a double-quoted HTML attribute (keeps &lt; etc. out of the way)
const attr = (s) => esc(s);
const canonicalUrl = (slug) => `${ORIGIN}/who-said/${slug}`;
const ogImageUrl = (slug) => `${ORIGIN}/og/${slug}.png`;
// decode entities + strip tags → plain text for JSON-LD string values
// Named HTML entities that show up in our prose/author names, mapped to their literal characters.
// Anything not here is decoded to its unicode char via the numeric fallback below when possible;
// only a genuinely unknown named entity collapses to a space. Accented Latin-1 letters matter:
// an author like "Barère" or "Brontë" must not render as "Bar re" in the plain-text FAQ/JSON-LD.
const NAMED_ENTITIES = {
  amp: '&', quot: '"', apos: "'", lt: '<', gt: '>', nbsp: ' ',
  mdash: '—', ndash: '–', middot: '·', hellip: '…', deg: '°', times: '×',
  ldquo: '"', rdquo: '"', lsquo: "'", rsquo: "'", laquo: '«', raquo: '»',
  agrave: 'à', aacute: 'á', acirc: 'â', atilde: 'ã', auml: 'ä', aring: 'å', aelig: 'æ',
  ccedil: 'ç', egrave: 'è', eacute: 'é', ecirc: 'ê', euml: 'ë',
  igrave: 'ì', iacute: 'í', icirc: 'î', iuml: 'ï', ntilde: 'ñ',
  ograve: 'ò', oacute: 'ó', ocirc: 'ô', otilde: 'õ', ouml: 'ö', oslash: 'ø', oelig: 'œ',
  ugrave: 'ù', uacute: 'ú', ucirc: 'û', uuml: 'ü', yacute: 'ý', yuml: 'ÿ', szlig: 'ß',
  Agrave: 'À', Aacute: 'Á', Acirc: 'Â', Atilde: 'Ã', Auml: 'Ä', Aring: 'Å', AElig: 'Æ',
  Ccedil: 'Ç', Egrave: 'È', Eacute: 'É', Ecirc: 'Ê', Euml: 'Ë',
  Igrave: 'Ì', Iacute: 'Í', Icirc: 'Î', Iuml: 'Ï', Ntilde: 'Ñ',
  Ograve: 'Ò', Oacute: 'Ó', Ocirc: 'Ô', Otilde: 'Õ', Ouml: 'Ö', Oslash: 'Ø', OElig: 'Œ',
  Ugrave: 'Ù', Uacute: 'Ú', Ucirc: 'Û', Uuml: 'Ü',
};
const plain = (x) => String(x || '').replace(/<[^>]+>/g, '')
  .replace(/&#(\d+);/g, (m, d) => String.fromCharCode(+d))
  .replace(/&#x([0-9a-f]+);/gi, (m, h) => String.fromCharCode(parseInt(h, 16)))
  .replace(/&([a-zA-Z]+);/g, (m, e) => (e in NAMED_ENTITIES ? NAMED_ENTITIES[e] : ' '))
  .replace(/\s+/g, ' ').trim();

const CONFIDENCE = {
  verified:   { cls: 'verified',   glyph: '✓', text: 'Verified',   label: 'Written by' },
  attributed: { cls: 'attributed', glyph: '≈', text: 'Attributed', label: 'Attributed to' },
  disputed:   { cls: 'disputed',   glyph: '?', text: 'Disputed',   label: 'Disputed attribution' },
};

// Rights status is a SEPARATE claim from attribution (who said it) — a quote can be firmly
// attributed and still under copyright. Three states, each with an honest default note; a record's
// own `source.rightsNote` prose, if present, replaces the default body but keeps the badge.
// `{holder}` in a default note is filled from `source.rightsHolder`. Marking a quote "in-copyright"
// is disclosure, not a licence: inclusion still rests on short-excerpt + commentary fair use.
const RIGHTS = {
  'public-domain': { label: 'Public domain', mark: '✓', accent: 'var(--sage)',
    note: 'This quotation is in the <strong>public domain</strong> and free to reuse. On Quotle.info, &ldquo;attribution verified&rdquo; and &ldquo;free to reuse&rdquo; are separate claims &mdash; here, both hold.' },
  'in-copyright':  { label: 'In copyright', mark: '©', accent: 'var(--amber)',
    note: 'This line is still <strong>under copyright</strong>{holder}. It is quoted here for identification and commentary; the complete work remains protected &mdash; verifying who said it is not a grant of reuse rights.' },
  'licensed':      { label: 'Used with permission', mark: '✓', accent: 'var(--sage)',
    note: 'Quoted <strong>with permission</strong>{holder}. Reuse rights belong to the rightsholder, not to Quotle.info.' },
};

// ---- <head> --------------------------------------------------------------
function renderHead(q) {
  const url = canonicalUrl(q.quoteSlug);
  const graph = buildJsonLd(q, url);
  const jsonLd = JSON.stringify(graph, null, 2)
    .split('\n').map((l, i) => (i === 0 ? l : '    ' + l)).join('\n');
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
${HEAD_SCRIPT}
    <title>${esc(q.meta.title)}</title>
    <meta name="version" content="${attr(q.meta.version)}">
    <meta name="gs-app-id" content="quotle-info">
    <meta name="description" content="${attr(q.meta.description)}">

    <!-- Per-page canonical + social. Every identity field derives from ONE canonical string:
         ${url}  (quoteSlug = kebab-case of the quote text, keyed to the quote not the author). -->
    <link rel="canonical" href="${url}">
    <meta property="og:type" content="article">
    <meta property="og:url" content="${url}">
    <meta property="og:title" content="${attr(q.meta.ogTitle)}">
    <meta property="og:description" content="${attr(q.meta.ogDescription)}">
    <meta property="og:site_name" content="Quotle.info">
    <meta property="og:image" content="${ogImageUrl(q.quoteSlug)}">
    <meta name="twitter:card" content="summary_large_image">

    <!-- Schema.org: Quotation + WebPage (emitted from the record; @ids derive from the canonical URL) -->
    <script type="application/ld+json">
    ${jsonLd}
    </script>

    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400&family=Source+Serif+4:ital,wght@0,300;0,400;0,600;1,300;1,400&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">

    <style>
${STYLE}${CHROME_CSS}
    </style>
${THEME_CSS}
</head>`;
}

function buildJsonLd(q, url) {
  const s = q.schema || {};
  const quotation = {
    '@type': 'Quotation',
    '@id': `${url}#quotation`,
    text: s.quotationText || q.fullQuote || q.displayQuote,
  };
  if (s.alternateName) quotation.alternateName = s.alternateName;
  if (s.creator) {
    quotation.creator = { '@type': 'Person', name: s.creator.name };
    if (s.creator.birthDate) quotation.creator.birthDate = s.creator.birthDate;
    if (s.creator.jobTitle) quotation.creator.jobTitle = s.creator.jobTitle;
    if (s.creator.sameAs) quotation.creator.sameAs = s.creator.sameAs;
  }
  if (s.dateCreated) quotation.dateCreated = s.dateCreated;
  if (s.isBasedOn) {
    const b = s.isBasedOn;
    quotation.isBasedOn = { '@type': b.type || 'CreativeWork', name: b.name };
    if (b.periodicalName) quotation.isBasedOn.isPartOf = { '@type': 'Periodical', name: b.periodicalName };
    if (b.datePublished) quotation.isBasedOn.datePublished = b.datePublished;
    if (b.pagination) quotation.isBasedOn.pagination = b.pagination;
    if (b.sameAs) quotation.isBasedOn.sameAs = b.sameAs;
  }
  // Rights → structured, so agents get reuse status without scraping prose.
  const rights = q.source && q.source.rights;
  if (rights === 'public-domain') {
    quotation.license = 'https://creativecommons.org/publicdomain/mark/1.0/';
    quotation.isAccessibleForFree = true;
  } else if (rights === 'in-copyright') {
    quotation.copyrightNotice = 'In copyright' + (q.source.rightsHolder ? ' — ' + plain(q.source.rightsHolder) : '');
  }
  if (rights) quotation.usageInfo = `${ORIGIN}/how-we-verify`;

  const webpage = {
    '@type': 'WebPage',
    '@id': url,
    name: s.webPageName || q.meta.ogTitle,
    dateModified: s.dateModified,
    publisher: { '@type': 'Organization', name: 'Quotle.info', url: ORIGIN },
    mainEntity: { '@id': `${url}#quotation` },
  };

  // ClaimReview — the canonical fact-check schema. Rates the claim "{who} said {quote}":
  // verified → the true author, true (5/5); attributed → plausible/unproven (3); disputed →
  // the popularly-credited (wrong) name, false (1). The Quotation.creator still names the REAL
  // author, so a machine reads both "the claim about {who} is {rating}" and "actually by {creator}".
  const RATING = { verified: [5, 'Verified'], attributed: [3, 'Attributed'], disputed: [1, 'Disputed'] };
  const [ratingValue, ratingName] = RATING[q.confidence] || RATING.verified;
  const trueAuthor = plain((q.answer && q.answer.authorName) || (s.creator && s.creator.name) || '');
  const firstMisWho = q.misattribution && q.misattribution.items && q.misattribution.items[0] && plain(q.misattribution.items[0].who);
  const claimant = (q.confidence === 'disputed' && firstMisWho) ? firstMisWho : trueAuthor;
  const quoteText = plain(quotation.text);
  const claimReview = {
    '@type': 'ClaimReview',
    '@id': `${url}#claimreview`,
    url,
    author: { '@type': 'Organization', name: 'Quotle.info', url: ORIGIN },
    datePublished: s.dateModified,
    claimReviewed: claimant ? `${claimant} said: "${quoteText}"` : `"${quoteText}"`,
    itemReviewed: {
      '@type': 'Claim',
      author: claimant ? { '@type': 'Person', name: claimant } : undefined,
      appearance: { '@id': `${url}#quotation` },
    },
    reviewRating: {
      '@type': 'Rating',
      ratingValue, bestRating: 5, worstRating: 1,
      alternateName: ratingName,
    },
  };
  if (!claimReview.itemReviewed.author) delete claimReview.itemReviewed.author;

  // FAQPage — the literal "Did {who} say {quote}?" Q&A, so AI answer-engines and snippets can
  // lift the verdict verbatim. Question uses the credited name; answer leads with the verdict.
  const verdictLead = q.confidence === 'disputed' ? 'No. ' : q.confidence === 'attributed' ? 'Not confirmed. ' : 'Yes. ';
  const answerText = (verdictLead + plain((q.answer && q.answer.sourceLine) || (q.answer && q.answer.label) || '')).replace(/\s+/g, ' ').trim();
  const faq = {
    '@type': 'FAQPage',
    '@id': `${url}#faq`,
    mainEntity: [{
      '@type': 'Question',
      name: claimant ? `Did ${claimant} say "${quoteText}"?` : `Who really said "${quoteText}"?`,
      acceptedAnswer: { '@type': 'Answer', text: answerText, url },
    }],
  };

  return { '@context': 'https://schema.org', '@graph': [quotation, claimReview, webpage, faq] };
}

// ---- top nav + breadcrumb ------------------------------------------------
function renderNav(q) {
  const a = q.author || {};
  const crumbName = authorLinked(a.slug)
    ? `<a href="/authors/${a.slug}">${esc(a.name)}</a>`
    : `<span>${esc(a.name)}</span>`;
  const crumbAuthor = a.name
    ? `${crumbName}<span class="sep" aria-hidden="true">›</span>\n        `
    : '';
  return `
${siteNav('')}
    <nav class="breadcrumb" aria-label="Breadcrumb">
        <a href="/">Home</a><span class="sep" aria-hidden="true">›</span>
        ${crumbAuthor}<span aria-current="page">${esc(q.breadcrumbLeaf || q.displayQuote)}</span>
    </nav>`;
}

// ---- Layer 1: the answer -------------------------------------------------
function renderAnswer(q) {
  const conf = CONFIDENCE[q.confidence] || CONFIDENCE.verified;
  const ans = q.answer || {};
  const label = ans.label || conf.label;
  const confText = ans.confidenceText || conf.text;
  const nameInner = (ans.authorHref && authorLinked(q.author && q.author.slug))
    ? `<a href="${attr(ans.authorHref)}">${esc(ans.authorName)}</a>`
    : esc(ans.authorName);
  const dates = ans.authorDates
    ? `\n                    <span class="author-dates">${esc(ans.authorDates)}</span>`
    : '';
  return `
        <!-- ============ LAYER 1: THE ANSWER ============ -->
        <article class="answer" aria-labelledby="quote-heading">
            <p class="kicker">${esc(ans.kicker || 'Who really said it')}</p>
            <h1 class="the-quote" id="quote-heading">${esc(q.displayQuote)}</h1>
            <div class="attribution-row">
                <div class="author-block">
                    <span class="lbl">${esc(label)}</span>
                    <span class="author-name">${nameInner}</span>${dates}
                </div>
                <span class="confidence ${conf.cls}">
                    <span class="dot" aria-hidden="true">${conf.glyph}</span>
                    <span><span class="visually-hidden">Attribution status: </span>${esc(confText)}</span>
                </span>
            </div>
            <p class="source-line">${ans.sourceLine}</p>
            <div class="actions">
                <button class="act-btn" id="copyBtn" type="button">Copy quote</button>
                <button class="act-btn" id="shareBtn" type="button">Share</button>
            </div>
            <p class="answer-foot">
                <span aria-hidden="true">🕓</span> Last verified ${esc(ans.lastVerified)} · <a href="/how-we-verify">how we verify</a>
            </p>
        </article>`;
}

// ---- The source ----------------------------------------------------------
function renderSource(q) {
  const src = q.source || {};
  const rows = (src.docMeta || [])
    .map((r) => `                    <dt>${esc(r.dt)}</dt><dd${r.ddClass ? ` class="${r.ddClass}"` : ''}>${r.dd}</dd>`)
    .join('\n');
  const cutTag = src.cutTag ? `\n                    <span class="cut-tag">${esc(src.cutTag)}</span>` : '';
  const excerptNote = src.excerptNote
    ? `\n                <p class="excerpt-note">${src.excerptNote}</p>` : '';
  const artifact = renderArtifact(src.artifact);
  const sourceLink = src.sourceLink
    ? `\n                <a class="source-link" href="${attr(src.sourceLink.url)}" target="_blank" rel="noopener">${esc(src.sourceLink.text)} <span aria-hidden="true">↗</span></a>` : '';
  const trail = (src.trail && src.trail.length)
    ? `\n                <div class="trail">
                    <p class="trail-title">${esc(src.trailTitle || 'How we verified this')}</p>
                    <ul>
${src.trail.map((li) => `                        <li>${li}</li>`).join('\n')}
                    </ul>
                </div>` : '';
  const rights = renderRights(src);
  const kicker = src.kicker || 'Provenance';
  const heading = src.heading || 'The source';
  return `
        <!-- ============ THE SOURCE ============ -->
        <section aria-labelledby="source-h">
            <div class="sec-head"><p class="kicker">${esc(kicker)}</p><h2 id="source-h">${esc(heading)}</h2></div>
            <div class="source-card">
                <dl class="doc-meta">
${rows}
                </dl>
                <p class="excerpt">
                    ${src.excerpt}${cutTag}
                </p>${excerptNote}${artifact}${sourceLink}${trail}${rights}
            </div>
        </section>`;
}

function renderArtifact(a) {
  if (!a) return '';
  return `
                <div class="artifact">
                    <span class="artifact-ic" aria-hidden="true">${esc(a.icon || '📄')}</span>
                    <div class="artifact-txt">
                        <div class="a-kind">${esc(a.kindLabel)}</div>
                        <a href="${attr(a.url)}" target="_blank" rel="noopener">${esc(a.linkText)}</a>
                    </div>
                </div>`;
}

function renderRights(src) {
  // Structured state wins; `publicDomain: true` is legacy shorthand for 'public-domain'.
  const state = src.rights || (src.publicDomain === true ? 'public-domain' : null);
  const r = state && RIGHTS[state];
  // No (recognized) state: fall back to legacy prose-only note for un-migrated records.
  if (!r) return src.rightsNote ? `\n                <p class="rights-note">${src.rightsNote}</p>` : '';
  const holder = src.rightsHolder ? ` of ${esc(src.rightsHolder)}` : '';
  const body = src.rightsNote || r.note.replace('{holder}', holder);
  return `
                <div class="rights rights-${state}">
                    <span class="rights-badge"><span class="rights-mark" aria-hidden="true">${r.mark}</span>${esc(r.label)}</span>
                    <p class="rights-body">${body}</p>
                </div>`;
}

// ---- Often misattributed (optional) --------------------------------------
function renderMisattribution(q) {
  const m = q.misattribution;
  if (!m) return '';
  const items = (m.items || []).map((it) => {
    const tag = it.tag ? ` <span class="false-tag">${esc(it.tag)}</span>` : '';
    return `                    <div class="false-item">
                        <span class="false-x" aria-hidden="true">✕</span>
                        <div>
                            <div class="false-who"><span class="visually-hidden">${esc(it.scope || 'Incorrectly attributed to ')}</span>${it.who}${tag}</div>
                            <p class="false-why">${it.why}</p>
                        </div>
                    </div>`;
  }).join('\n');
  const truth = m.truthLine ? `
                <div class="truth-line">
                    <span class="dot" aria-hidden="true">✓</span>
                    <span>${m.truthLine}</span>
                </div>` : '';
  return `
        <!-- ============ OFTEN MISATTRIBUTED ============ -->
        <section aria-labelledby="misattr-h">
            <div class="sec-head"><p class="kicker">${esc(m.kicker || 'Fact-check')}</p><h2 id="misattr-h">${esc(m.heading || 'Often misattributed')}</h2></div>
            <div class="misattr">
                <p class="misattr-intro">${m.intro}</p>
                <div class="false-list">
${items}
                </div>${truth}
            </div>
        </section>`;
}

// ---- Why it mattered (optional) ------------------------------------------
function renderContext(q) {
  const c = q.context;
  if (!c) return '';
  const leadArr = Array.isArray(c.lead) ? c.lead : (c.lead ? [c.lead] : []);
  const lead = leadArr.map((p) => `            <p>${p}</p>`).join('\n');
  const pull = c.pull ? `\n            <p class="pull">${c.pull}</p>` : '';
  const details = c.detailsBody && c.detailsBody.length ? `
            <details>
                <summary>${esc(c.detailsSummary || 'Read the full story')}</summary>
                <div class="body">
${c.detailsBody.map((p) => `                    <p>${p}</p>`).join('\n')}
                </div>
            </details>` : '';
  return `
        <!-- ============ WHY IT MATTERED ============ -->
        <section class="story" aria-labelledby="story-h">
            <div class="sec-head"><p class="kicker">${esc(c.kicker || 'Context')}</p><h2 id="story-h">${esc(c.heading || 'Why it mattered')}</h2></div>
${lead}${pull}${details}
        </section>`;
}

// ---- Related quotes (optional) -------------------------------------------
function renderRelated(q) {
  if (!q.related || !q.related.length) return '';
  const cards = q.related.map((r) => `                <a class="connect-card" href="/who-said/${r.slug}">
                    <p class="connect-quote">&ldquo;${r.quote}&rdquo;</p>
                    <div class="connect-foot"><span class="connect-author">${esc(r.author)}</span><span class="connect-rel">${r.rel}</span></div>
                </a>`).join('\n');
  return `
        <!-- ============ RELATED QUOTES ============ -->
        <section aria-labelledby="connect-h">
            <div class="sec-head"><p class="kicker">Explore</p><h2 id="connect-h">Related quotes</h2></div>
            <div class="connect-grid">
${cards}
            </div>
        </section>`;
}

// ---- Dig deeper (always) -------------------------------------------------
function renderResearch(q) {
  const items = (q.externalLinks || []).map((l, idx) => `                <a class="research-item" href="/cite/?q=${encodeURIComponent(q.quoteSlug)}&i=${idx}" data-ext="${attr(l.url)}">
                    <div class="research-top"><span class="research-label">${esc(l.label)}</span><span class="research-host">${esc(l.host)}</span><span class="research-arrow" aria-hidden="true">→</span></div>
                    <p class="research-what">${l.what}</p>
                </a>`).join('\n');
  return `
        <!-- ============ DIG DEEPER ============ -->
        <section aria-labelledby="research-h">
            <div class="sec-head"><p class="kicker">Go further</p><h2 id="research-h">Dig deeper</h2></div>
            <p class="research-intro">${q.researchIntro || 'Trusted places to keep pulling the thread — primary archives, fact-checks, and scholarship. We show how we used each one before you leave.'}</p>
            <div class="research-list">
${items}
            </div>
            <p class="cite-skip-note" id="citeSkipNote" hidden>You&rsquo;re skipping our source pages &mdash; these links now open the source directly. <a href="#" id="citeSkipReset">Show them again</a></p>
        </section>
        <script>
        (function(){
            var skip=false; try{ skip=localStorage.getItem('quotle-skip-cite')==='1'; }catch(e){}
            var note=document.getElementById('citeSkipNote');
            if(skip){ [].forEach.call(document.querySelectorAll('.research-item'),function(a){ var ext=a.getAttribute('data-ext'); if(ext){ a.setAttribute('href',ext); a.setAttribute('target','_blank'); a.setAttribute('rel','noopener nofollow'); } }); if(note) note.hidden=false; }
            var r=document.getElementById('citeSkipReset');
            if(r) r.addEventListener('click',function(e){ e.preventDefault(); try{ localStorage.removeItem('quotle-skip-cite'); }catch(e){} location.reload(); });
        })();
        </script>`;
}

// ---- About the author (always) -------------------------------------------
function renderAuthor(q) {
  const a = q.author || {};
  const nameInner = authorLinked(a.slug) ? `<a href="/authors/${a.slug}">${esc(a.name)}</a>` : esc(a.name);
  return `
        <!-- ============ ABOUT THE AUTHOR ============ -->
        <section aria-labelledby="author-h">
            <div class="sec-head"><p class="kicker">${esc(a.kicker || 'The author')}</p><h2 id="author-h">${esc(a.heading || ('About ' + a.name))}</h2></div>
            <div class="author-card">
                <div class="author-avatar" aria-hidden="true">${esc(a.initials || '')}</div>
                <div>
                    <p class="a-name">${nameInner}</p>
                    <p class="a-meta">${esc(a.metaLine || '')}</p>
                    <p>${a.bio}</p>
                </div>
            </div>
        </section>`;
}

// ---- Cite this (always) --------------------------------------------------
function renderCite(q) {
  const url = canonicalUrl(q.quoteSlug);
  const cite = q.cite || {};
  const pageCite = cite.pageCitation
    || `Quotle.info. &ldquo;${esc(q.meta.ogTitle)}&rdquo; Last verified ${esc((q.answer || {}).lastVerified || '')}.`;
  return `
        <!-- ============ CITE THIS PAGE ============ -->
        <section aria-labelledby="cite-h">
            <div class="sec-head"><p class="kicker">For writers &amp; researchers</p><h2 id="cite-h">Cite this</h2></div>
            <div class="cite">
                <div class="cite-block">
                    <div class="cite-lbl"><span>${esc(cite.sourceLabel || 'The primary source (Chicago)')}</span><button class="cite-copy" data-copy="src" type="button">Copy</button></div>
                    <p class="cite-text" id="citeSrc">${cite.sourceCitation}</p>
                </div>
                <div class="cite-block">
                    <div class="cite-lbl"><span>This verification page</span><button class="cite-copy" data-copy="page" type="button">Copy</button></div>
                    <p class="cite-text" id="citePage">${pageCite} <code>${url}</code></p>
                </div>
            </div>
        </section>`;
}

// ---- Prev / next (optional) ----------------------------------------------
function renderPager(q) {
  if (!q.pager) return '';
  const p = q.pager;
  const prev = p.prev ? `
            <a href="/who-said/${p.prev.slug}">
                <div class="dir">← Previous</div>
                <div class="pq">${p.prev.pq}</div>
            </a>` : '';
  const next = p.next ? `
            <a class="next" href="/who-said/${p.next.slug}">
                <div class="dir">Next →</div>
                <div class="pq">${p.next.pq}</div>
            </a>` : '';
  return `
        <!-- ============ PREV / NEXT ============ -->
        <nav class="pager" aria-label="More quotes">${prev}${next}
        </nav>`;
}

// ---- Game CTA + footer + script (constant except copy attribution) -------
function renderTail(q) {
  const copyAttr = (q.copyAttribution != null)
    ? q.copyAttribution
    : `— ${(q.answer || {}).authorName || ''}`;
  return `
        <!-- ============ GAME CTA ============ -->
        <aside class="game-cta" aria-label="Related game">
            <p class="cta-title">Think you know your quotes?</p>
            <p>Quotle is a daily puzzle: guess the author from the words alone.</p>
            <a class="game-cta-btn" href="https://gameshelf.co/quotle/" target="_blank" rel="noopener">Play today's Quotle <span aria-hidden="true">→</span></a>
        </aside>
    </main>

    <footer>
        <p>quotle<span style="color:var(--burgundy)">.info</span> — every attribution traced to a primary source and dated. A <a href="https://gameshelf.co">Game Shelf</a> project.</p>
    </footer>

    <div class="toast" id="toast" role="status" aria-live="polite">Copied</div>

    <script>
        const quoteText = document.getElementById('quote-heading').textContent.trim();
        const copyAttribution = ${JSON.stringify(copyAttr)};
        function toast(msg){ const t=document.getElementById('toast'); t.textContent=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),1800); }
        async function copy(text, label){ try { await navigator.clipboard.writeText(text); toast(label||'Copied'); } catch(e){ toast('Copy failed'); } }
        document.getElementById('copyBtn').addEventListener('click', () => copy('"'+quoteText+'" '+copyAttribution, 'Copied'));
        document.getElementById('shareBtn').addEventListener('click', async () => {
            const data = { title: 'Quotle.info', text: '"'+quoteText+'" '+copyAttribution, url: location.href };
            if (navigator.share) { try { await navigator.share(data); } catch(e){} } else { copy(data.text+' '+data.url, 'Link copied'); }
        });
        document.querySelectorAll('.cite-copy').forEach(btn => btn.addEventListener('click', () => {
            const el = document.getElementById(btn.dataset.copy === 'src' ? 'citeSrc' : 'citePage');
            copy(el.textContent.trim(), 'Citation copied');
        }));
    </script>
${SEARCH_JS}
${SCRIPT}
</body>
</html>`;
}

// ---- top-level -----------------------------------------------------------
function renderPage(q) {
  validate(q);
  return renderHead(q)
    + '\n<body>\n'
    + renderNav(q)
    + '\n\n    <main>'
    + renderAnswer(q)
    + renderSource(q)
    + renderMisattribution(q)
    + renderContext(q)
    + renderRelated(q)
    + renderResearch(q)
    + renderAuthor(q)
    + renderCite(q)
    + renderPager(q)
    + renderTail(q);
}

function validate(q) {
  const need = ['quoteSlug', 'displayQuote', 'confidence', 'meta', 'answer', 'source', 'author'];
  for (const k of need) if (!q[k]) throw new Error(`record ${q.quoteSlug || '?'} missing required field: ${k}`);
  if (!CONFIDENCE[q.confidence]) throw new Error(`record ${q.quoteSlug}: bad confidence "${q.confidence}"`);
  if (q.source.rights && !RIGHTS[q.source.rights]) throw new Error(`record ${q.quoteSlug}: bad rights "${q.source.rights}" (use public-domain|in-copyright|licensed)`);
  if (!/^[a-z0-9-]+$/.test(q.quoteSlug)) throw new Error(`record ${q.quoteSlug}: slug must be kebab-case`);
}

// ---- the frozen stylesheet (verbatim from quote-v3.html) -----------------
const STYLE = `${ROOT_CSS}
        * { margin: 0; padding: 0; box-sizing: border-box; }
        html { scroll-behavior: smooth; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; }
        body { font-family: 'Source Serif 4', Georgia, serif; background: var(--bg-deep); color: var(--ink); line-height: 1.7; overflow-x: hidden; }
        body::before { content: ''; position: fixed; inset: 0; background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.03'/%3E%3C/svg%3E"); pointer-events: none; z-index: 9999; }
        a { color: inherit; }
        a:focus-visible, button:focus-visible { outline: 2px solid var(--sage); outline-offset: 3px; border-radius: 4px; }
        .visually-hidden { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0; }

        .topnav { display: flex; align-items: center; justify-content: space-between; max-width: 780px; margin: 0 auto; padding: 20px 24px 8px; }
        .brand { display: flex; align-items: center; gap: 9px; text-decoration: none; }
        .brand-icon { width: 30px; height: 30px; border-radius: 8px; background: linear-gradient(135deg, var(--burgundy), var(--burgundy-deep)); display: grid; place-items: center; font-size: 0.95rem; }
        .brand-name { font-family: 'Playfair Display', serif; font-weight: 900; font-size: 1.05rem; }
        .brand-name span { color: var(--burgundy); }
        .nav-verify { font-family: 'DM Sans', sans-serif; font-size: 0.78rem; font-weight: 500; color: var(--sage); text-decoration: none; display: inline-flex; align-items: center; gap: 6px; padding: 7px 13px; border: 1px solid rgba(126,179,139,0.3); border-radius: 999px; transition: background 0.2s; }
        .nav-verify:hover { background: var(--sage-dim); }
        .breadcrumb { max-width: 780px; margin: 0 auto; padding: 6px 24px 0; font-family: 'DM Sans', sans-serif; font-size: 0.75rem; color: var(--text-muted); }
        .breadcrumb a { text-decoration: none; }
        .breadcrumb a:hover { color: var(--slate); }
        .breadcrumb .sep { margin: 0 7px; opacity: 0.6; }

        main { max-width: 700px; margin: 0 auto; padding: 8px 24px 60px; }
        .kicker { font-family: 'DM Sans', sans-serif; text-transform: uppercase; font-size: 0.7rem; font-weight: 600; letter-spacing: 0.2em; color: var(--burgundy); margin-bottom: 14px; }
        section { margin-top: 52px; }
        .sec-head { margin-bottom: 20px; }
        .sec-head .kicker { margin-bottom: 8px; }
        .sec-head h2 { font-family: 'Playfair Display', serif; font-weight: 900; font-size: 1.7rem; letter-spacing: -0.015em; }

        /* ===== LAYER 1 — THE ANSWER (sealed container) ===== */
        .answer { margin-top: 18px; padding: 34px 32px 26px; background: linear-gradient(180deg, rgba(26,26,46,0.9), rgba(26,26,46,0.35)); border: 1px solid rgba(255,255,255,0.09); border-radius: var(--radius-lg); box-shadow: 0 20px 60px rgba(0,0,0,0.25); }
        .the-quote { font-family: 'Playfair Display', serif; font-weight: 700; font-size: clamp(1.9rem, 6vw, 2.8rem); line-height: 1.22; letter-spacing: -0.015em; margin: 4px 0 24px; text-wrap: balance; }
        .the-quote::before { content: '\\201C'; color: var(--burgundy); opacity: 0.4; margin-right: 2px; }
        .the-quote::after { content: '\\201D'; color: var(--burgundy); opacity: 0.35; margin-left: 3px; vertical-align: -0.15em; }

        .attribution-row { display: flex; flex-wrap: wrap; align-items: center; gap: 12px 16px; margin-bottom: 18px; }
        .author-block { display: flex; flex-direction: column; }
        .author-block .lbl { font-family: 'DM Sans', sans-serif; font-size: 0.66rem; text-transform: uppercase; letter-spacing: 0.14em; color: var(--text-muted); }
        .author-name { font-family: 'DM Sans', sans-serif; font-weight: 700; font-size: 1.1rem; color: var(--gold); }
        .author-name a { text-decoration: none; }
        .author-name a:hover { text-decoration: underline; }
        .author-dates { font-family: 'DM Sans', sans-serif; font-size: 0.76rem; color: var(--text-muted); }

        /* 3-state confidence — distinct hue AND distinct glyph per state (not color alone) */
        .confidence { display: inline-flex; align-items: center; gap: 8px; font-family: 'DM Sans', sans-serif; font-weight: 600; font-size: 0.78rem; padding: 7px 13px; border-radius: 999px; border: 1px solid; }
        .confidence .dot { width: 16px; height: 16px; border-radius: 50%; display: grid; place-items: center; font-size: 0.68rem; font-weight: 700; color: var(--bg-deep); }
        .confidence.verified   { color: var(--sage);   background: var(--sage-dim);            border-color: rgba(126,179,139,0.35); }
        .confidence.verified .dot   { background: var(--sage); }
        .confidence.attributed { color: var(--amber);  background: rgba(224,162,78,0.12);      border-color: rgba(224,162,78,0.35); }
        .confidence.attributed .dot { background: var(--amber); }
        .confidence.disputed   { color: var(--caution); background: rgba(138,147,201,0.14);    border-color: rgba(138,147,201,0.4); }
        .confidence.disputed .dot   { background: var(--caution); }

        .source-line { font-family: 'DM Sans', sans-serif; font-size: 0.88rem; color: var(--slate); padding-top: 16px; border-top: 1px solid var(--border); }
        .source-line strong { color: var(--ink); font-weight: 600; }
        .actions { display: flex; gap: 10px; margin-top: 20px; }
        .act-btn { font-family: 'DM Sans', sans-serif; font-size: 0.82rem; font-weight: 500; color: var(--slate); background: var(--bg-elevated); border: 1px solid var(--border); border-radius: var(--radius-sm); padding: 9px 16px; cursor: pointer; transition: background 0.2s, color 0.2s; }
        .act-btn:hover { background: var(--bg-card-hover); color: var(--ink); }
        .answer-foot { margin-top: 18px; padding-top: 14px; border-top: 1px solid var(--border); font-family: 'DM Sans', sans-serif; font-size: 0.74rem; color: var(--text-muted); display: flex; align-items: center; gap: 7px; }
        .answer-foot a { color: var(--sage); text-decoration: none; }
        .answer-foot a:hover { text-decoration: underline; }

        /* ===== THE SOURCE ===== */
        .source-card { background: var(--bg-card); border: 1px solid var(--border); border-radius: var(--radius-lg); padding: 30px 28px; position: relative; overflow: hidden; }
        .source-card::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px; background: var(--sage); opacity: 0.7; }
        .doc-meta { display: grid; grid-template-columns: auto 1fr; gap: 8px 18px; margin-bottom: 22px; }
        .doc-meta dt { font-family: 'DM Sans', sans-serif; font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.12em; color: var(--text-muted); padding-top: 4px; }
        .doc-meta dd { font-size: 0.98rem; }
        .doc-meta dd.title { font-style: italic; }
        .excerpt { padding: 4px 0 4px 18px; border-left: 2px solid var(--sage); margin: 6px 0 12px; font-size: 1.05rem; color: var(--ink); }
        .excerpt .cut-tag { display: inline-block; font-family: 'DM Sans', sans-serif; font-size: 0.64rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: var(--sage); background: var(--sage-dim); padding: 1px 7px; border-radius: 4px; margin-left: 8px; vertical-align: middle; }
        .excerpt-note { font-family: 'DM Sans', sans-serif; font-size: 0.82rem; color: var(--slate); margin: 12px 0 22px; }
        .artifact { display: flex; gap: 14px; align-items: center; background: var(--cream); border: 1px solid var(--border); border-radius: var(--radius-md); padding: 14px 16px; margin-bottom: 22px; }
        .artifact-ic { width: 40px; height: 40px; border-radius: var(--radius-sm); background: var(--bg-elevated); display: grid; place-items: center; font-size: 1.2rem; flex-shrink: 0; }
        .artifact-txt .a-kind { font-family: 'DM Sans', sans-serif; font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.1em; color: var(--text-muted); }
        .artifact-txt a { color: var(--sage); text-decoration: none; font-family: 'DM Sans', sans-serif; font-weight: 600; font-size: 0.9rem; }
        .artifact-txt a:hover { text-decoration: underline; }
        .source-link { display: inline-flex; align-items: center; gap: 8px; font-family: 'DM Sans', sans-serif; font-weight: 600; font-size: 0.88rem; color: var(--sage); background: var(--sage-dim); border: 1px solid rgba(126,179,139,0.35); padding: 11px 20px; border-radius: var(--radius-sm); text-decoration: none; transition: background 0.2s; }
        .source-link:hover { background: rgba(126,179,139,0.2); }

        /* Verification trail — block rows, hanging check, prose flow (no ragged flex columns) */
        .trail { margin-top: 26px; padding-top: 22px; border-top: 1px solid var(--border); }
        .trail-title { font-family: 'DM Sans', sans-serif; font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.14em; color: var(--sage); font-weight: 600; margin-bottom: 14px; }
        .trail ul { list-style: none; display: flex; flex-direction: column; gap: 12px; }
        .trail li { position: relative; padding-left: 24px; font-size: 0.92rem; color: var(--slate); line-height: 1.6; }
        .trail li::before { content: '✓'; position: absolute; left: 0; top: 0; color: var(--sage); font-weight: 700; }
        .trail a { color: var(--ink); text-decoration: underline; text-decoration-color: rgba(126,179,139,0.55); text-underline-offset: 2px; }
        .trail a:hover { text-decoration-color: var(--sage); }
        .rights-note { margin-top: 20px; font-family: 'DM Sans', sans-serif; font-size: 0.82rem; color: var(--slate); background: var(--cream); border-left: 2px solid var(--amber); border-radius: 0 var(--radius-sm) var(--radius-sm) 0; padding: 13px 16px; line-height: 1.6; }
        .rights-note strong { color: var(--ink); }
        /* Rights status (separate claim from attribution): badge + honest note, accent per state. */
        .rights { margin-top: 20px; background: var(--cream); border-left: 2px solid var(--border); border-radius: 0 var(--radius-sm) var(--radius-sm) 0; padding: 12px 16px 13px; }
        .rights-public-domain { border-left-color: var(--sage); }
        .rights-in-copyright { border-left-color: var(--amber); }
        .rights-licensed { border-left-color: var(--sage); }
        .rights-badge { display: inline-flex; align-items: center; gap: 6px; font-family: 'DM Sans', sans-serif; font-size: 0.63rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.11em; margin-bottom: 6px; }
        .rights-public-domain .rights-badge, .rights-licensed .rights-badge { color: var(--sage); }
        .rights-in-copyright .rights-badge { color: var(--amber); }
        .rights-mark { font-size: 0.9rem; line-height: 1; }
        .rights-body { font-family: 'DM Sans', sans-serif; font-size: 0.82rem; color: var(--slate); line-height: 1.6; margin: 0; }
        .rights-body strong { color: var(--ink); }

        /* ===== MISATTRIBUTION ===== */
        .misattr { background: linear-gradient(135deg, var(--burgundy-glow), transparent); border: 1px solid var(--border-accent); border-radius: var(--radius-lg); padding: 30px 28px; }
        .misattr-intro { color: var(--slate); margin-bottom: 22px; }
        .false-list { display: flex; flex-direction: column; gap: 16px; }
        .false-item { display: flex; gap: 14px; align-items: flex-start; padding-bottom: 16px; border-bottom: 1px solid var(--border); }
        .false-item:last-child { border-bottom: none; padding-bottom: 0; }
        .false-x { width: 24px; height: 24px; border-radius: 50%; flex-shrink: 0; background: rgba(212,98,122,0.15); color: var(--burgundy); display: grid; place-items: center; font-weight: 700; font-size: 0.85rem; margin-top: 2px; }
        .false-who { font-family: 'DM Sans', sans-serif; font-weight: 600; color: var(--ink); }
        .false-tag { font-family: 'DM Sans', sans-serif; font-size: 0.62rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: var(--text-muted); border: 1px solid var(--border); border-radius: 4px; padding: 1px 6px; margin-left: 8px; vertical-align: middle; }
        .false-why { font-size: 0.92rem; color: var(--slate); margin-top: 2px; }
        .false-why a { color: var(--burgundy-link); text-decoration: underline; text-underline-offset: 2px; }
        .truth-line { margin-top: 24px; padding: 16px 18px; background: var(--sage-dim); border-radius: var(--radius-md); display: flex; gap: 12px; align-items: flex-start; }
        .truth-line .dot { width: 22px; height: 22px; border-radius: 50%; background: var(--sage); color: var(--bg-deep); display: grid; place-items: center; font-size: 0.8rem; font-weight: 700; flex-shrink: 0; margin-top: 1px; }
        .truth-line span { font-size: 0.94rem; }
        .truth-line a { color: var(--sage); text-decoration: underline; text-underline-offset: 2px; }

        /* ===== STORY ===== */
        .story summary { font-family: 'DM Sans', sans-serif; font-size: 0.9rem; font-weight: 600; color: var(--burgundy-link); cursor: pointer; list-style: none; display: inline-flex; align-items: center; gap: 8px; }
        .story summary::-webkit-details-marker { display: none; }
        .story summary::after { content: '↓'; transition: transform 0.2s; }
        .story details[open] summary::after { transform: rotate(180deg); }
        .story .body { margin-top: 16px; }
        .story p { margin-bottom: 16px; color: var(--ink); }
        .story .body p:last-child { margin-bottom: 0; }
        .pull { font-family: 'Playfair Display', serif; font-style: italic; font-size: 1.3rem; line-height: 1.4; color: var(--gold); margin: 24px 0; padding-left: 20px; border-left: 3px solid var(--gold); }

        /* ===== RELATED ===== */
        .connect-grid { display: flex; flex-direction: column; gap: 12px; }
        .connect-card { display: block; text-decoration: none; background: var(--bg-card); border: 1px solid var(--border); border-radius: var(--radius-md); padding: 22px 24px; transition: transform 0.25s, border-color 0.25s; }
        .connect-card:hover { transform: translateY(-3px); border-color: var(--border-accent); }
        .connect-quote { font-style: italic; font-size: 1.05rem; margin-bottom: 12px; color: var(--ink); }
        .connect-foot { display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; }
        .connect-author { font-family: 'DM Sans', sans-serif; font-weight: 600; font-size: 0.85rem; color: var(--gold); }
        .connect-rel { font-family: 'DM Sans', sans-serif; font-size: 0.8rem; color: var(--text-muted); }

        /* ===== DIG DEEPER ===== */
        .research-intro { color: var(--slate); margin-bottom: 20px; }
        .research-list { display: flex; flex-direction: column; gap: 8px; }
        .research-item { display: block; text-decoration: none; padding: 15px 18px; border-radius: var(--radius-md); border: 1px solid var(--border); background: var(--bg-card); transition: border-color 0.2s, transform 0.2s; }
        .research-item:hover { border-color: var(--border-accent); transform: translateY(-2px); }
        .research-top { display: flex; align-items: center; gap: 10px; }
        .research-label { font-family: 'DM Sans', sans-serif; font-weight: 600; font-size: 0.95rem; color: var(--ink); }
        .research-arrow { color: var(--burgundy); margin-left: auto; transition: transform 0.2s; }
        .research-item:hover .research-arrow { transform: translateX(3px); }
        .research-what { font-size: 0.88rem; color: var(--slate); margin-top: 4px; }
        .cite-skip-note { font-family: 'DM Sans', sans-serif; font-size: 0.78rem; color: var(--text-muted); margin-top: 16px; }
        .cite-skip-note a { color: var(--burgundy); text-decoration: none; } .cite-skip-note a:hover { text-decoration: underline; }
        .research-host { font-family: 'DM Sans', sans-serif; font-size: 0.66rem; text-transform: uppercase; letter-spacing: 0.08em; color: var(--text-muted); border: 1px solid var(--border); border-radius: 4px; padding: 2px 7px; }

        /* ===== AUTHOR ===== */
        .author-card { background: var(--bg-card); border: 1px solid var(--border); border-radius: var(--radius-lg); padding: 26px 28px; display: flex; gap: 20px; align-items: flex-start; }
        .author-avatar { width: 54px; height: 54px; border-radius: 50%; flex-shrink: 0; background: linear-gradient(135deg, var(--burgundy), var(--purple)); display: grid; place-items: center; font-family: 'Playfair Display', serif; font-weight: 900; font-size: 1.4rem; color: white; }
        .author-card .a-name { font-family: 'Playfair Display', serif; font-size: 1.2rem; margin-bottom: 4px; }
        .author-card .a-name a { text-decoration: none; }
        .author-card .a-name a:hover { text-decoration: underline; }
        .author-card .a-meta { font-family: 'DM Sans', sans-serif; font-size: 0.78rem; color: var(--text-muted); margin-bottom: 10px; }
        .author-card p { font-size: 0.94rem; color: var(--slate); }

        /* ===== CITE THIS ===== */
        .cite { background: var(--cream); border: 1px solid var(--border); border-radius: var(--radius-lg); padding: 26px 28px; }
        .cite-block { margin-bottom: 18px; }
        .cite-block:last-of-type { margin-bottom: 0; }
        .cite-lbl { font-family: 'DM Sans', sans-serif; font-size: 0.66rem; text-transform: uppercase; letter-spacing: 0.12em; color: var(--text-muted); margin-bottom: 6px; display: flex; align-items: center; justify-content: space-between; }
        .cite-copy { font-family: 'DM Sans', sans-serif; font-size: 0.72rem; font-weight: 600; color: var(--sage); background: var(--sage-dim); border: 1px solid rgba(126,179,139,0.35); border-radius: var(--radius-sm); padding: 5px 11px; cursor: pointer; }
        .cite-copy:hover { background: rgba(126,179,139,0.2); }
        .cite-text { font-family: 'DM Sans', sans-serif; font-size: 0.85rem; color: var(--slate); line-height: 1.6; }
        .cite-text code { color: var(--slate); word-break: break-all; font-size: 0.82rem; }

        /* ===== PREV/NEXT ===== */
        .pager { display: flex; gap: 12px; margin-top: 48px; }
        .pager a { flex: 1; text-decoration: none; background: var(--bg-card); border: 1px solid var(--border); border-radius: var(--radius-md); padding: 16px 18px; transition: border-color 0.2s; }
        .pager a:hover { border-color: var(--border-accent); }
        .pager .dir { font-family: 'DM Sans', sans-serif; font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.1em; color: var(--text-muted); }
        .pager .pq { font-style: italic; font-size: 0.92rem; color: var(--ink); margin-top: 4px; }
        .pager .next { text-align: right; }

        /* ===== GAME CTA ===== */
        .game-cta { margin-top: 56px; text-align: center; background: linear-gradient(135deg, var(--burgundy-glow), var(--gold-dim)); border: 1px solid var(--border-accent); border-radius: var(--radius-lg); padding: 38px 28px; }
        .game-cta .cta-title { font-family: 'Playfair Display', serif; font-size: 1.4rem; margin-bottom: 8px; }
        .game-cta p { color: var(--slate); font-size: 0.95rem; margin-bottom: 20px; }
        .game-cta-btn { display: inline-flex; align-items: center; gap: 10px; padding: 14px 32px; background: linear-gradient(135deg, var(--burgundy), var(--burgundy-deep)); border-radius: var(--radius-md); font-family: 'DM Sans', sans-serif; font-weight: 600; color: white; text-decoration: none; transition: transform 0.2s, box-shadow 0.2s; }
        .game-cta-btn:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(212,98,122,0.4); }

        footer { text-align: center; padding: 40px 24px; color: var(--text-muted); font-family: 'DM Sans', sans-serif; font-size: 0.8rem; border-top: 1px solid var(--border); margin-top: 40px; }
        footer a { color: var(--burgundy-link); text-decoration: none; }
        .toast { position: fixed; bottom: 24px; left: 50%; transform: translateX(-50%) translateY(20px); background: var(--sage); color: var(--bg-deep); font-family: 'DM Sans', sans-serif; font-weight: 600; font-size: 0.85rem; padding: 10px 22px; border-radius: 999px; opacity: 0; pointer-events: none; transition: opacity 0.25s, transform 0.25s; z-index: 200; }
        .toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }

        @media (prefers-reduced-motion: reduce) {
            html { scroll-behavior: auto; }
            * { transition: none !important; animation: none !important; }
        }

        @media (max-width: 560px) {
            .the-quote { font-size: 1.9rem; }
            .doc-meta { grid-template-columns: 1fr; gap: 2px; }
            .doc-meta dt { padding-top: 12px; }
            .attribution-row { flex-direction: column; align-items: flex-start; }
            .source-card, .misattr, .author-card, .answer, .cite { padding: 22px 20px; }
            .pager { flex-direction: column; }
            .pager .next { text-align: left; }
        }`;

module.exports = { renderPage, canonicalUrl, ogImageUrl, CONFIDENCE };
